PRAGMA foreign_keys=OFF;
PRAGMA user_version=1;
BEGIN TRANSACTION;
DROP TABLE IF EXISTS android_metadata;
CREATE TABLE IF NOT EXISTS android_metadata (locale TEXT);
INSERT INTO "android_metadata" VALUES('en_US');
DROP TABLE IF EXISTS rules;
CREATE TABLE IF NOT EXISTS rules (appUID INTEGER PRIMARY KEY,appName TEXT NOT NULL,onionType TEXT NOT NULL DEFAULT "Tor",onionPort INTEGER NOT NULL DEFAULT '9040',portType TEXT NOT NULL DEFAULT "TransProxy");
{{REPLACE_WITH_GENERATED_SQL}}
COMMIT;
