#!/usr/bin/env python3
"""
Call the MIA python module directly.
"""

import os
import sys

# Add the script root the the PYTHONPATH environment variable.
ROOT = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
sys.path.append(ROOT)

if __name__ == '__main__':
    import mia.__main__
    mia.__main__.main()
